name: AWS_DEPLOY

on:
  push:
    branches: [main]

jobs:
  Build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@main
      - name: Create .env ( file )
        run: echo 'NODE_LOCAL_PORTS=${{ secrets.NODE_LOCAL_PORTS }}' > .env && echo 'NODE_DOCKER_PORTS=${{ secrets.NODE_DOCKER_PORTS }}' > .env && echo 'TOKEN_KEY_API=${{ secrets.TOKEN_KEY_API }}' > .env

      - name: Run build
        run: docker-compose up -d
