name: CD Pipeline

on:
  workflow_run:
    workflows: ['CI Pipeline']
    types:
      - completed

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Pull Docker image
        run: sudo docker pull devngl91/node-api-bot-rate-limit-9m8dya9osydn897abgsdnasdadasdas:latest
      - name: Delete Old docker container
        run: sudo docker rm -f node-api-bot-rate-limit-9m8dya9osydn897abgsdnasdadasdas-container || true
      - name: Run Docker container
        run: sudo docker run -d -p 3000:3000 --name node-api-bot-rate-limit-9m8dya9osydn897abgsdnasdadasdas-container devngl91/node-api-bot-rate-limit-9m8dya9osydn897abgsdnasdadasdas
